thumbtack/thumbprint-ios

Thumbprint/Targets/Thumbprint/Layouts/CarouselLayout.swift
Enable Thumbprint consumers to subclass `CarouselLayout` to override
the default spacing.
=> Change CarouselLayout from public => open

Thumbprint/Targets/Thumbprint/Components/Button.swift, Thumbprint/Targets/Thumbprint/Layouts/CarouselLayout.swift
Currently at runtime, the following warning is printed to the console
when CarouselLayout is used: "UICollectionViewFlowLayout has cached
frame mismatch for index path ... This is likely occurring because the
flow layout subclass CarouselLayout is modifying attributes returned
by UICollectionViewFlowLayout without copying them."
Address this by copying the UICollectionViewLayoutAttributes
instances returned by the super implementation before modifying them.
=> Fix warnings caused by carousel layout

Thumbprint/Targets/Thumbprint/Layouts/CarouselLayout.swift
Enable consumers of CarouselLayout to set custom spacing without
having to subclass it and override the property.
=> Preserve setter for CarouselLayout properties

.github/scripts/set_podspec_version.sh, .github/workflows/release.yml
Automate the process of releasing new versions of the Thumbprint
pod by defining a GitHub Action that can be triggered manually,
taking as input the version number to assign to the new release.
=> Create manual GitHub Action to publish new release

Thumbprint/Targets/Thumbprint/Components/Chips/Chip.swift, Thumbprint/Targets/Thumbprint/Components/Pill.swift
This pr adds the ability to drop in a custom `ChipPill`
Example Client Side Usage:
Say we have a one off subclass with some new parameters
```
// MARK: - Larger Pill
final private class ChipPillLarge: ChipPill {
override class var defaultHeight: CGFloat {
48.0
}
override class var textStyle: Font.TextStyle {
return .title7
}
}
```
We can now construct our `Chip` / Subclass with the new `ChipPill`
`let chip = ToggleChip(pill: ChipPillLarge())`
=> Allow a custom ChipPill within Chip

README.md
Adds a badge to the README showing the latest version of the cocoapod, as well as license under which Thumbprint is released:
=> Add badge to README for pod version and license

Thumbprint/Targets/Thumbprint/Components/Button.swift, Thumbprint/Targets/ThumbprintTests/Unit/Components/ButtonUnitTest.swift, Thumbprint/Thumbprint.xcodeproj/project.pbxproj
Currently `Button`'s `accessibilityLabel` uses `title` as its value and cannot be set. This PR makes it so `Button` will allow `accessibilityLabel` to be set and use `title` if it isn't set.
=> Allow Button's accessibility label to be set

.github/scripts/commit_release.sh, .github/scripts/tag_release.sh, .github/workflows/release.yml
When releasing new versions, the release action automatically creates
a PR bumping the pod version. However by default, push actions
triggered by another action do not trigger the usual push event. Using
a separate personal access token disables this behavior.
=> Fix automated release version bump PRs

.github/scripts/commit_release.sh
As pointed out in https://github.com/thumbtack/thumbprint-ios/pull/34,
the regular expression used by the release script did not handle
some valid cases (e.g., "10.11.12", or prerelease versions like
"10.11.12-beta").
Update the pattern to use a version of that recommended by
https://semver.org.
=> Improve release version regex pattern

Thumbprint/Targets/Thumbprint/Components/Footer.swift
We want to remove the SnapKit dependency from Thumbprint, this PR cleans it up for the Footer component.
The only real logical difference between the old behavior and the new one is that we're letting the shadow maintain its height based on its intrinsicContentSize. As it's the same as the height we were forcing and we don't expect anything to affect the shadow view's height otherwise we should be good. If not CI will let us know quick enough.
=> Migrated Footer component out of SnapKit

Thumbprint/Targets/Thumbprint/Presentations/Sheet/PartialSheetPresentationController.swift
- add present/dismiss notifications for partial sheets
These notifications are intended to be used in cases where the overall application hierarchy needs to respond to presentation or dismissal events from partial sheets.
=> Add present/dismiss notifications for partial sheets

Podfile, Podfile.lock
PRs are failing due to a build warning about the SwiftFormat pod's
deployment target being set to iOS 7.0, which is too low. Given that we
don't actually care about supporting iOS versions that far back, add a
workaround to the Podfile to set all pods' deployment targets equal to
whatever deployment target we have set for Thumbprint as a whole.
=> Work around SwiftFormat deployment target issue

.github/workflows/ci.yml, Podfile.lock, Thumbprint/Targets/Playground/Classes/Inspectable/InspectableViews/EntityAvatar+InspectableView.swift, Thumbprint/Targets/Playground/Classes/Inspectable/InspectableViews/UserAvatar+InspectableView.swift, Thumbprint/Targets/Thumbprint/Components/Avatar.swift, Thumbprint/Targets/Thumbprint/Components/UserAvatar.swift, Thumbprint/Targets/ThumbprintTests/Snapshot/Components/AvatarTest.swift
Update the `Avatar.Size` API to include a public constructor, enabling
one-off sizes to be constructed as needed.
=> Support custom Avatar sizes

Thumbprint/Targets/Thumbprint/Components/EntityAvatar.swift, Thumbprint/Targets/Thumbprint/Components/UserAvatar.swift
Reverting thumbtack/thumbprint-ios#61
The background color property is meant to be something managed purely by the Avatar initial logic as a fallback to not having an image.
=> Revert "Made avatar background color property public"

Thumbprint/Targets/Thumbprint/Components/TextArea.swift
TextArea has nothing in it to notify for text change events in realtime. We have to rely on `NSTextStorageDelegate` to figure out real time text changes. Added a `sendAction` call for `.editingChanged`.
=> TextArea: Added sendAction call to notify of text changes in real time

Thumbprint/Targets/Thumbprint/Components/EntityAvatar.swift, Thumbprint/Targets/Thumbprint/Components/UserAvatar.swift
Previously, avatars had required sizes because they were being explicitly constrained.  Since removing those constraints, we are now relying on the avatars `preferredContentSize`, which negotiates conflicts by using the view's contentHuggingPriority and contentCompressionResistancePriority.  UIView's have a default contentHuggingPriority of 250 and a default compressionResistancePriority of 750.  Setting these both to 800 in both directions ensures that the value will always be higher than any view's default priority.
=> Set default content compression/hugging priorities for avatars

Thumbprint/Targets/Thumbprint/Components/TextArea.swift
TextArea component is missing 'editingDidBegin' action broadcasting
=> Broadcast editingDidBegin action

Thumbprint/Targets/Thumbprint/Components/Slider.swift
Update the access level of the slider to `open` to allow subclassing in other modules
=> Update access level of slider to open

Thumbprint/Targets/Thumbprint/Components/Chips/Chip.swift, Thumbprint/Targets/Thumbprint/Components/Pill.swift
We have code in our iOS app that need to set default height as Pill to label. Currently it is set differently and in an attempt to modify pill default height it may disturb UI for that particular view ([here](https://github.com/thumbtack/ios/pull/11695#discussion_r935877353)). Exposing these class vars to allow thumbtack iOS codebase to utilize these values as well it will allow subclass to override these for specific cases.
=> Making Pill class var public

Thumbprint/Targets/Playground/Classes/PlaygroundViewController.swift, Thumbprint/Targets/Thumbprint/Components/Chips/Chip.swift, Thumbprint/Targets/Thumbprint/Components/Pill.swift
Made a mistake in my previous [PR](https://github.com/thumbtack/thumbprint-ios/pull/100)
Instead of making class var open for overridable made them public. This is a fix for it.
=> Making pill class var open

Thumbprint/Targets/Thumbprint/Components/Pill.swift
- Removed logic that sets iconSize in Config as this doesn't actually work to change the icon size.
- Made the `iconImageView` property public so that subclasses can access it and customize its layout/size.
=> Made Pill component's  iconImageView property public

Thumbprint/Targets/Thumbprint/Icons.swift
Needed to add small navigation sync icon for Engagement landing page [error retry view](https://www.figma.com/file/dVM3MYRzREKzgn1oqwILW2/Native-Landing-Page?node-id=652%3A48451&t=aw99BPbO8qRMMK8A-4).
=> Add small navigation sync icon

Thumbprint/Targets/Thumbprint/Components/ShadowCard.swift
Added functionality to `ShadowCard` to allow setting/updating `shadowImage` after view initialization. This is required for a server driven UI feature where we need to update the shadow based on BE response.
I manually verified this works by pointing ios repo to local thumbprint-ios.
=> Update ShadowCard to support updating shadowImage

Package.resolved, Package.swift
- Pinning exact version of dependencies
- Using swiftlint auto fix plugin:
=> Specify exact version for dependencies + using swiftlint plugin to autofix

Package.swift
there is a bug in xcode where the package.resolve is ignored https://github.com/apple/swift-package-manager/pull/6578
=> [SPM] Pinning to exact library versions

Package.swift, Tests/ThumbprintTests/Snapshot/Components/LoaderDotsTest.swift, Tests/ThumbprintTests/Snapshot/Presentations/PartialSheetTest.swift
I'm not sure why entirely, but it seems also snapshot tests were removed during the move to SPM. I think it's because we were trying to disable one test which was broken, so i've re-enabled snapshot tests, but disabled that particular text.
=> Re-enable snapshot tests as they were disabled for some reason as part of the move to SPM

Sources/Thumbprint/Icons.swift
Icon asset already exists in `ios` repo
=> Add tiny notification icon mapping

Sources/Thumbprint/Icons.swift
Mapping the small wave icon. It is needed for one of the cards on the Home Tab on iOS
=> Add small waves icon mapping

Sources/Thumbprint/Components/Dropdown.swift, Thumbprint/Thumbprint.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Adding a minor patch for a bug where the `selectedIndex` of `Dropdown` can potentially be set to `-1` by the `pickerView.selectedRow` API.
This change inspects the selected row and only updates the selected if the index is non-negative.
=> Fix index out of bounds issue with dropdown

Sources/Thumbprint/Presentations/Sheet/PartialSheetPresentationController.swift
We had disabled panning in partial sheets due to a bug that I've now narrowed down to Apple's implementation. In my testing the described issue no longer occurs. The clients will still have to re-enable panning after this is merged.
=> Partial sheet panning fix

Package.resolved, Package.swift, Sources/Thumbprint/Components/Button.Theme.swift, Sources/Thumbprint/Components/Pill.swift, Sources/Thumbprint/Font.swift, Sources/Thumbprint/Presentations/Presentation.swift, Sources/Thumbprint/Presentations/Sheet/PartialSheetPresentation.swift, Thumbprint/Thumbprint.xcodeproj/project.pbxproj, Thumbprint/Thumbprint.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Did change only these so we could migrate membership to complete
- set concurrency checking to complete
- Upgrade thumbprint token to 13.0.3
- Fix host app and playground not building
TODO:
=> Make Pill, button and PartialSheetPresentation sendable + Update package resolved

Sources/Thumbprint/Presentations/Sheet/PartialSheetPresentation.swift, Sources/Thumbprint/Presentations/Sheet/PartialSheetPresentationController.swift
Adds an additional boolean argument, `interactively`, to the partialSheetPresentationControllerDidDismissSheet() method of PartialSheetPresentationControllerDelegate.  This value is set to true when the dismissal of the modal is triggered by user interaction with the modal container (tapping the darkened background area or swiping down on the modal), rather than with the contents of the model itself.
=> Add "interactively" parameter to partial sheet presentation delegate

Sources/Thumbprint/Components/Avatar.swift
Make size sendable in Avatar to fix this waning:
[static property 'small' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6](https://next-jenkins.thumbtack.io/job/verify-ios-pr/job/PR-18553/3/console) in browse
=> [COMPLETE] Make Size sendable in Avatar

Sources/Thumbprint/Components/Toast.swift
Allows toasts to adjust themselves upward and downward in response to the software keyboard being presented or dismissed.
https://github.com/user-attachments/assets/3d74d11c-25cc-4312-9ea8-4877e62aa51d
=> Allow toasts to adjust for keyboard presentation
